### PR TITLE
Fixed require: changed MD5 to md5

### PR DESCRIPTION
**Pull request by lisandro52**
To complete the changes introduced for #56

### CODE REVIEW

**Comment by benkaiser** [comment]
Please change the package.json` file also.

**Comment by benkaiser** [comment]
Actually take that back. Looks all good. Merging now.

**Comment by ohnx** [comment]
Ha! Seems like I forgot to change it there.

Thanks, @lisandro52.

**Comment by lisandro52** [comment]
No problemo! I'm glad that I'll now be able to test an alternative to Cherrymusic. 
And thanks to you for finding the original solution, I just made a little followup patch.

**Comment by benkaiser** [comment]
Yeah let me know what you think of it and how it compares :)

**Pull request merged**
