### PR TITLE
App integration

### PR DESCRIPTION
**Pull request by ohnx**
I have written a simple app for node-music-player called [nmp-client](https://github.com/ohnx/nmp-client) in C#.
It's pretty much just a window with a browser in it.
It catches the system media keys and can play/pause/skip/back the songs as well, but these minor changes are needed in order to make things work properly.

### CODE REVIEW

**Comment by benkaiser** [comment]
Thanks for the interest in the project!

I'm guessing what you are trying to achieve here is to have the commands control the play behaviour of the app? If so there is already a way to do that!

I noticed your `integreation.js` file simply wraps around the `player.someMethod()` calls, can you simply invoke the method on `player` from csharp?

Anyway how I have it working, is that you can run nmp through a browser, click the button in the bottom right `Remote Setup` and set the computer name. Then you can fire off calls to the server to remote control that terminal!
e.g. If I named my machine `example` then I can fire off the following calls:
```
// toggle play state
http://localhost:2000/command/example/playpause
// previous track
http://localhost:2000/command/example/prev
// next track
http://localhost:2000/command/example/next
```

And under linux I let my window manager ([i3](https://i3wm.org/)) do all the key binding / request:
```
bindsym $mod+XF86AudioPlay exec curl http://localhost:2000/command/example/playpause
bindsym $mod+XF86AudioPrev exec curl http://localhost:2000/command/example/prev
bindsym $mod+XF86AudioNext exec curl http://localhost:2000/command/example/next
```

I don't know what the equivalent in windows is, but just find some application that can fire requests to urls on keybinding.
http://www.autohotkey.com/ might be one tool that could do the job. Otherwise you could just use your app to sit in the background and recognise the hotkeys.

**Comment by ohnx** [comment]
I'm currently using the built in web browser, so the `player.` functions can't be called.
I suppose that I could fire HTTP requests in my app as well, but since it's already open, it's easier to just control it from the app itself.

**Comment by Shuunen** [comment]
On my side on Windows 7, I have curl so I created a shortcut which point to :
`curl http://localhost:2000/command/example/playpause`
Then go to the shortcut properties and set a Shortcut key :
image

That's it ! All works well without using any third party app :)

**Comment by benkaiser** [comment]
Boom.  @Shuunen nailed it.
Don't know if it's possible, but can you save those shortcuts / upload them? or would they be computer-specific (other than the port number / localhost of course)?

Anyway thanks, I'll mark this as closed now.

**Comment by ohnx** [comment]
They are `.lnk` files, so they should be able to be shared.

**Comment by Shuunen** [comment]
> Boom. @Shuunen nailed it.
\o/

And yes it can be uploaded but users will have to adapt it to their environment : server, port and they will have to install curl too

**Comment by ohnx** [comment]
@Shuunen can you set a media function key (ie, next) for a shortcut key?

**Comment by benkaiser** [comment]
Oh okay, yeah I didn't mind so much depending on the ports and host. But depending on curl sucks. From a quick search it doesn't look like there is a good windows command-line url fetching tool.
But yeah I guess we could add it as a wiki or maybe to the readme, the process for setting it up on windows.

I'm also interested to know if it works with media keys too.

**Comment by Shuunen** [comment]
humm I think it should work :) but I have no media keys on my keyboard to test it :)

**Pull request closed without merging**
